- id: gitgud
  name: Gid Gud
  entry: gitgud
  description: Git Gud brings Dark Souls to programming. Are you brave enough?
  language: python
  pass_filenames: false
  stages: [pre-commit]
  verbose: true