- id: darksouls
  name: Dark Souls
  entry: darksouls
  description: Xtreme programming Dark Souls style. Are you brave enough?
  language: python
  pass_filenames: false
  stages: [pre-commit]
  verbose: true