- id: darksouls
  name: Darksouls
  entry: darksouls
  description: Xtreme programming Darksouls style. Are you brave enough?
  language: python
  pass_filenames: false
  stages: [pre-commit]
  verbose: true